### ISSUE TITLE
Make the app translatable

### ISSUE THREAD

**Issue by NathanBnm** [rkoesters/xkcd-gtk#52]

**Comment by rkoesters** [comment]
From what I can tell, the xkcd API doesn't support fetching non-english versions of the comic. Is this request purely for the user interface?

**Comment by NathanBnm** [comment]
Yes that's for the user Interface and description in `appdata.xml` ans `.desktop` files.

Maybe I can précise that comics are on english in `appdata.xml` translation.

I can translate the app into French.

**Comment by rkoesters** [comment]
I have the template file prepared: https://github.com/rkoesters/xkcd-gtk/blob/master/po/com.github.rkoesters.xkcd-gtk.pot

Any pull requests that add translations are welcome.

**Comment by NathanBnm** [comment]
@rkoesters where are the files `LINGUAS` and `POTFILES` ? As recommended in the elementary documentation (https://elementary.io/fr/docs/code/getting-started#Adding-Translations)

**Comment by rkoesters** [comment]
@NathanBnm I have added `LINGUAS` and `POTFILES` in addition to preparing the appdata and desktop files for translation.

I still have a couple tasks before this is ready:

- [ ] Install compiled gettext files (`*.mo`)
- [ ] Make sure the keyboard shortcuts window can be translated (I might have to restructure how it gets loaded in order to support translations)
